import { JetBrains_Mono } from 'next/font/google'; // Import font
import Header from '@/components/header'; // Import Header component
import "./globals.css"; // Import Global CSS
import Head from 'next/head'; // Import Next.js Head component
import PageTransition from '@/components/ui/PageTransition'; 
import StairTransition from '@/components/ui/StairTransition';

const jetBrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-jetbrains', // Assign variable for use
});

export const metadata = {
  title: "Jerry Vishal",
  description: "Generated by next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jetBrainsMono.variable}>
        <Header /> 
        <StairTransition></StairTransition>
        <PageTransition>{children}</PageTransition>
        
      </body>
    </html>
  );
}